language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - gaoyibobobo@gmail.com
    on_success: change
    on_failure: always

install:
  - npm install

script:
  - sh build.sh

after_script:
  - cd dist
  - git init
  - git remote add origin https://${REF}
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - REF=github.com/riskers/share.git # 设置 github 地址